### ISSUE TITLE
Min and max can't be set on in6 for the it8792 chip using the it87 driver

### ISSUE THREAD

**Issue by konomikitten** [cooper151288/it87#1] opened 2018-11-21 10:56 UTC
## Issue

Min and max can't be set on in6 (and possibly others) for the it8792 chip using the it87 driver.

### Testing

````
bash ~
# cat /sys/class/hwmon/hwmon1/in6_min
2780
bash ~
# echo 2779 > /sys/class/hwmon/hwmon1/in6_min
bash ~
# cat /sys/class/hwmon/hwmon1/in6_min
2780
bash ~
# cat /sys/class/hwmon/hwmon1/in6_max
2780
bash ~
# echo 2781 > /sys/class/hwmon/hwmon1/in6_max
bash ~
# cat /sys/class/hwmon/hwmon1/in6_max
2780
bash ~
# echo 2779 > /sys/class/hwmon/hwmon1/in6_max
bash ~
# cat /sys/class/hwmon/hwmon1/in6_max
2780
bash ~
# cat /sys/class/hwmon/hwmon1/name
it8792
bash ~
$
````

### Config

````
$ cat /etc/sensors.d/GA-AB350-GAMING3.conf 
# The temp3 temperature offset depends on the CPU type and needs to be
# adjusted. Compare against the output of k10temp for the correct value.

# The temp3 temperature offset depends on the CPU type and needs to be
# adjusted. Compare against the output of k10temp for the correct value.

chip "it8686-isa-0a40"
  label temp1 "System 1"
  label temp2 "Chipset"
  label temp3 "CPU Socket"
  label temp4 "PCI-EX16"
  label temp5 "VRM MOS"
  label temp6 "vSOC MOS"
  label in0 "CPU Vcore"
  label in1 "+3.3v"
  label in2 "+12v"
  label in3 "+5v"
  label in4 "CPU Vcore SOC"
  label in5 "CPU Vddp"
  label in6 "DRAM A/B"
  label in7 "3VSB"
  label in8 "Battery"
  label fan1 "CPU_FAN"
  label fan2 "SYS_FAN1"
  label fan3 "SYS_FAN2"
  label fan4 "SYS_FAN3_PUMP"
  label fan5 "CPU_OPT"

#  compute temp3 @+15,@/15
  compute in1 @*1.650,@/1.650
  compute in2 @*6,@/6
  compute in3 @*2.5,@/2.5

  set in0_min 0.6
  set in0_max 1.45
  set in1_min 3.135
  set in1_max 3.465
  set in2_min 11.400
  set in2_max 12.600
  set in3_min 4.750
  set in3_max 5.250
  set in6_min 1.2 * 0.97
  set in6_max 1.2 * 1.2
  set in7_min 3.3 * 0.97
  set in7_max 3.3 * 1.05

chip "it8792-isa-0a60"
  label temp1 "PCI-EX8"
  label temp2 "Temp 2"
  label temp3 "System 2"
  label in0 "CPU Vcore"
  label in1 "DDR VTT"
  label in2 "Chipset Core"
  label in3 "VIN3"
  label in4 "CPU Vdd18"
  label in5 "DDR Vpp"
  label in6 "3VSB"
  label in7 "Battery"

  compute in6 @*1.20,@/1.20

  set in0_min 0.6
  set in0_max 1.45
  set in6_min 3.135
  set in6_max 3.465
  set in7_min 3.3 * 0.97
  set in7_max 3.3 * 1.03

  ignore fan1
  ignore fan2
  ignore fan3
  ignore in8
bash ~
$ 
````

### isadump

````
$ sudo grep it87 /proc/ioports
    0a45-0a46 : it87
      0a45-0a46 : it87
  0a65-0a66 : it87
    0a65-0a66 : it87
bash ~
$ 
````

````
$ sudo isadump 0xa45 0xa46
WARNING! Running this program can cause system crashes, data loss and worse!
I will probe address register 0xa45 and data register 0xa46.
Continue? [Y/n] Y
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00: 19 10 00 80 df ff 08 20 ff 98 48 00 00 a4 97 00 
10: ff ff ff 37 c7 c8 c8 00 01 01 00 ff ff ff ff ff 
20: 4b a8 a8 a9 68 4d 73 88 86 27 37 26 14 32 35 80 
30: 79 32 af 9e af 9e af 9e ff 00 ff 00 78 61 90 85 
40: 7f 7f 7f 7f 7f 7f 5f 40 ad 6a d4 00 00 00 00 00 
50: ff 18 7f 7f 7f 40 00 00 90 00 19 12 65 00 00 00 
60: 00 14 41 46 1c 03 00 00 00 14 3c 46 1c 03 00 ff 
70: 00 14 41 46 1c 03 00 3e 00 00 96 00 00 00 0f 98 
80: 00 00 00 00 ff ff ff ff 00 00 00 00 00 e1 00 dd 
90: 00 00 00 00 ff 10 30 30 42 99 00 00 01 38 f2 26 
a0: 00 00 96 00 00 0a 0f 98 7f 7f 96 80 00 00 0f 98 
b0: 56 ea 87 7a 7f 00 88 00 88 00 3c 3c 3c 3c 3c 3c 
c0: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
d0: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 01 
e0: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
f0: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
bash ~
$ 
````
````
$ sudo isadump 0xa65 0xa66
WARNING! Running this program can cause system crashes, data loss and worse!
I will probe address register 0xa65 and data register 0xa66.
Continue? [Y/n] Y
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00: 19 10 00 00 ff ff 00 00 00 80 48 00 30 ff ff ff 
10: ff ff ff 77 c7 00 00 00 ff ff ff ff ff ff ff ff 
20: 52 53 53 99 6a 5f ff 98 97 22 29 2b 80 a6 f2 f2 
30: 85 37 ff 00 ff 00 ff 00 ff 00 ff 00 ff ff 9c 93 
40: 7f 7f 7f 7f 7f 7f 5f 40 ad 6a d4 00 ff ff ff ff 
50: ff 38 7f 7f 7f 80 00 00 90 00 0b 12 60 00 00 00 
60: 00 14 41 46 1c 03 00 ff 00 14 41 46 1c 03 00 ff 
70: 00 14 41 46 1c 03 00 ff ff ff ff 80 ff ff ff ff 
80: ff ff ff ff ff ff ff ff 00 00 00 00 00 d2 00 2d 
90: ff 00 00 00 ff 00 00 00 05 97 00 00 40 b0 c1 ac 
a0: d3 f2 59 74 7e 08 c5 2b 30 ab 6f d1 3f 33 00 00 
b0: 56 56 57 56 55 57 b7 e7 ff ff ff ff ff ff ff ff 
c0: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
d0: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
e0: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
f0: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
bash ~
$ 
````

### git

````
$ git config --local --list
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=https://github.com/cooper151288/it87.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
bash ~
$ 
````

````
$ git rev-parse HEAD
5515f5b78838cb6be551943ffef5d1792012724c
bash ~
$
````

**Comment by cooper151288** [comment] 2018-11-22 08:18
Is there anything that can be set (and isn't ignored) on the 8792?- what I'll trying to find out is whether the whole chip is ignored or just the in_min/max ones.

The driver does mention your board. Was something to do with lockups being caused by using the configuration mode.

What I'd advise to try after trying to write values in to see if they are dropped is to try the ignore_resource_conflict and the MMIO parameters (syntax should be clear in README and source)- this should rule out funky firmware. Save your work/backup critical data first.

Thanks for the register dumps. I'll attempt to decode these (without a datasheet) to recreate what you have in sysfs. If I can locate the register for the min/max that you are having problems with, it may be worth checking to see if we can manually set the register to your desired value with isaset.

All this may take me a while, unfortunately, as I am not too experienced with the driver code side of things- I am a test engineer by trade and this is free. By keeping this on the issues page, publicly available, we can make sure everything is well documented and improve it87 significantly.

**Comment by cooper151288** [comment] 2018-11-22 10:00
3 tachos enabled on 8792, 2 enabled on 8686? Can I have the output from the sensors cmd please?- might be useful to see what is connected to which chip.

**Comment by cooper151288** [comment] 2018-11-22 10:04
Your in6 min/max registers (if it's the same as 8728) are 0xff ie highest possible value. Ill dig into the code and see what reg it should be...

**Comment by cooper151288** [comment] 2018-11-22 12:00
Plugging this into the in_from_reg function I get 27800 (I'm missing a factor of 10 here, it'll be elsewhere in the code)

**Comment by cooper151288** [comment] 2018-11-22 12:33
Try a value 2769 or lower in sysfs for the in6_min. The driver should have complained about an out of range value in the first place
2769 would correspond with 0xfe being set as the value.
You could also try:
isaset 0xa65 0xa66 0x3d 0xfe
(This should do the same thing but bypass the driver)- you should see in6_min=2769 if it works

**Comment by cooper151288** [comment] 2018-11-22 14:29
Does sysfs say 2780 on in6_input, in6_min and in6_max? Need to see if my sheet is right for 8792

**Comment by cooper151288** [comment] 2018-11-23 16:42
If this solves the problem, can you let me know so I can close the issue?

**Comment by konomikitten** [comment] 2018-11-23 17:56
> Is there anything that can be set (and isn't ignored) on the 8792?- what I'll trying to find out is whether the whole chip is ignored or just the in_min/max ones.

Yes I was able to set other values

> Can I have the output from the sensors cmd please?- might be useful to see what is connected to which chip.

This is without the configuration file.

````
$ sensors
k10temp-pci-00c3
Adapter: PCI adapter
Tdie:         +47.9°C  (high = +70.0°C)
Tctl:         +47.9°C
  
it8686-isa-0a40
Adapter: ISA adapter
in0:          +1.27 V  (min =  +0.00 V, max =  +3.06 V)
in1:          +2.00 V  (min =  +0.00 V, max =  +3.06 V)
in2:          +2.02 V  (min =  +0.00 V, max =  +3.06 V)
in3:          +2.02 V  (min =  +0.00 V, max =  +3.06 V)
in4:          +1.25 V  (min =  +0.00 V, max =  +3.06 V)
in5:          +0.90 V  (min =  +0.00 V, max =  +3.06 V)
in6:          +1.39 V  (min =  +0.00 V, max =  +3.06 V)
3VSB:         +3.26 V  (min =  +0.00 V, max =  +6.12 V)
Vbat:         +3.24 V  
fan1:        1785 RPM  (min =    0 RPM)
fan2:        1859 RPM  (min =    0 RPM)
temp1:        +47.0°C  (low  = +127.0°C, high = +127.0°C)  sensor = thermistor
temp2:        +62.0°C  (low  = +127.0°C, high = +127.0°C)  sensor = thermistor
temp3:        +50.0°C  (low  = +127.0°C, high = +127.0°C)  sensor = AMD AMDSI
temp4:        +21.0°C  (low  =  +0.0°C, high = +127.0°C)  sensor = thermistor
temp5:        +58.0°C  (low  =  +0.0°C, high = -120.0°C)  sensor = thermistor
temp6:        +61.0°C  (low  =  +0.0°C, high = -120.0°C)  sensor = thermistor
intrusion0:  ALARM

it8792-isa-0a60
Adapter: ISA adapter
in0:          +1.22 V  (min =  +0.00 V, max =  +2.78 V)
in1:          +0.93 V  (min =  +0.00 V, max =  +2.78 V)
in2:          +0.85 V  (min =  +0.00 V, max =  +2.78 V)
+3.3V:        +3.33 V  (min =  +0.00 V, max =  +5.56 V)
in4:          +1.08 V  (min =  +0.00 V, max =  +2.78 V)
in5:          +0.94 V  (min =  +0.00 V, max =  +2.78 V)
in6:          +2.78 V  (min =  +0.00 V, max =  +2.78 V)  ALARM
3VSB:         +3.31 V  (min =  +0.00 V, max =  +5.56 V)
Vbat:         +3.29 V
fan1:           0 RPM  (min =    0 RPM)
fan2:           0 RPM  (min =    0 RPM)
fan3:           0 RPM  (min =    0 RPM)
temp1:        +38.0°C  (low  = +127.0°C, high = +127.0°C)  sensor = thermistor
temp2:        +45.0°C  (low  = +127.0°C, high = +127.0°C)  sensor = thermistor
temp3:        +47.0°C  (low  = +127.0°C, high = +127.0°C)  sensor = thermistor
intrusion0:  ALARM
  
bash ~
$
````

````
bash ~
$ sensors -u
k10temp-pci-00c3
Adapter: PCI adapter
Tdie:
  temp1_input: 37.875
  temp1_max: 70.000
Tctl:
  temp2_input: 37.875

it8686-isa-0a40
Adapter: ISA adapter
in0:
  in0_input: 0.408
  in0_min: 0.000
  in0_max: 3.060
  in0_alarm: 0.000
  in0_beep: 0.000
in1:
  in1_input: 2.016
  in1_min: 0.000
  in1_max: 3.060
  in1_alarm: 0.000
  in1_beep: 0.000
in2:
  in2_input: 2.016
  in2_min: 0.000
  in2_max: 3.060
  in2_alarm: 0.000
  in2_beep: 0.000
in3:
  in3_input: 2.028
  in3_min: 0.000
  in3_max: 3.060
  in3_alarm: 0.000
  in3_beep: 0.000
in4:
  in4_input: 1.248
  in4_min: 0.000
  in4_max: 3.060
  in4_alarm: 0.000
  in4_beep: 0.000
in5:
  in5_input: 0.912
  in5_min: 0.000
  in5_max: 3.060
  in5_alarm: 0.000
  in5_beep: 0.000
in6:
  in6_input: 1.380
  in6_min: 0.000
  in6_max: 3.060
  in6_alarm: 0.000
  in6_beep: 0.000
3VSB:
  in7_input: 3.264
  in7_min: 0.000
  in7_max: 6.120
  in7_alarm: 0.000
  in7_beep: 0.000
Vbat:
  in8_input: 3.240
fan1:
  fan1_input: 1785.000
  fan1_min: 0.000
  fan1_alarm: 0.000
  fan1_beep: 1.000
fan2:
  fan2_input: 1844.000
  fan2_min: 0.000
  fan2_alarm: 0.000
  fan2_beep: 1.000
temp1:
  temp1_input: 43.000
  temp1_max: 127.000
  temp1_min: 127.000
  temp1_alarm: 0.000
  temp1_type: 4.000
  temp1_offset: 0.000
  temp1_beep: 1.000
temp2:
  temp2_input: 60.000
  temp2_max: 127.000
  temp2_min: 127.000
  temp2_alarm: 0.000
  temp2_type: 4.000
  temp2_offset: 0.000
  temp2_beep: 1.000
temp3:
  temp3_input: 37.000
  temp3_max: 127.000
  temp3_min: 127.000
  temp3_alarm: 0.000
  temp3_type: 5.000
  temp3_offset: 0.000
  temp3_beep: 1.000
temp4:
  temp4_input: 21.000
  temp4_max: 127.000
  temp4_min: 0.000
  temp4_alarm: 0.000
  temp4_type: 4.000
  temp4_offset: 0.000
  temp4_beep: 1.000
temp5:
  temp5_input: 54.000
  temp5_max: -120.000
  temp5_min: 0.000
  temp5_alarm: 0.000
  temp5_type: 4.000
  temp5_offset: 0.000
  temp5_beep: 1.000
temp6:
  temp6_input: 56.000
  temp6_max: -120.000
  temp6_min: 0.000
  temp6_alarm: 0.000
  temp6_type: 4.000
  temp6_offset: 0.000
  temp6_beep: 1.000
intrusion0:
  intrusion0_alarm: 1.000

it8792-isa-0a60
Adapter: ISA adapter
in0:
  in0_input: 0.392
  in0_min: 0.000
  in0_max: 2.780
  in0_alarm: 0.000
in1:
  in1_input: 0.719
  in1_min: 0.000
  in1_max: 2.780
  in1_alarm: 0.000
in2:
  in2_input: 0.818
  in2_min: 0.000
  in2_max: 2.780
  in2_alarm: 0.000
+3.3V:
  in3_input: 3.335
  in3_min: 0.000
  in3_max: 5.559
  in3_alarm: 0.000
in4:
  in4_input: 1.123
  in4_min: 0.000
  in4_max: 2.780
  in4_alarm: 0.000
in5:
  in5_input: 0.992
  in5_min: 0.000
  in5_max: 2.780
  in5_alarm: 0.000
in6:
  in6_input: 2.780
  in6_min: 0.000
  in6_max: 2.780
  in6_alarm: 1.000
3VSB:
  in7_input: 3.314
  in7_min: 0.000
  in7_max: 5.559
  in7_alarm: 0.000
Vbat:
  in8_input: 3.292
fan1:
  fan1_input: 0.000
  fan1_min: 0.000
  fan1_alarm: 0.000
fan2:
  fan2_input: 0.000
  fan2_min: 0.000
  fan2_alarm: 0.000
fan3:
  fan3_input: 0.000
  fan3_min: 0.000
  fan3_alarm: 0.000
temp1:
  temp1_input: 36.000
  temp1_max: 127.000
  temp1_min: 127.000
  temp1_alarm: 0.000
  temp1_type: 4.000
  temp1_offset: 0.000
temp2:
  temp2_input: 43.000
  temp2_max: 127.000
  temp2_min: 127.000
  temp2_alarm: 0.000
  temp2_type: 4.000
  temp2_offset: 0.000
temp3:
  temp3_input: 45.000
  temp3_max: 127.000
  temp3_min: 127.000
  temp3_alarm: 0.000
  temp3_type: 4.000
  temp3_offset: 0.000
intrusion0:
  intrusion0_alarm: 1.000

bash ~
$ 
````


> Try a value 2769 or lower in sysfs for the in6_min.

````
bash ~
# cat /sys/class/hwmon/hwmon1/name
it8792
bash ~
# cat /sys/class/hwmon/hwmon1/in6_min
0
bash ~
# echo 2769 > /sys/class/hwmon/hwmon1/in6_min
bash ~
# cat /sys/class/hwmon/hwmon1/in6_min
2769
bash ~
# 
````

> Does sysfs say 2780 on in6_input, in6_min and in6_max?

````
bash ~
# cat /sys/class/hwmon/hwmon1/name 
it8792
bash ~
# cat /sys/class/hwmon/hwmon1/in6_input 
2780
bash ~
# cat /sys/class/hwmon/hwmon1/in6_min
0
# cat /sys/class/hwmon/hwmon1/in6_max
2780
bash ~
# 
````

**Comment by cooper151288** [comment] 2018-11-24 17:02
Thanks for checking all this out- was unsure if your board was properly supported by this driver. I'll close the issue, but if you have any questions, just ask. The diagnostic info will be useful for checking the driver code and documenting undocumented chips. Pretty sure a similar board has been checked on this driver but sometimes similar boards are wildly different.

**Closed as completed** 2018-11-24 17:02 UTC

**Comment by cooper151288** [comment] 2018-11-24 17:30
Are the register dumps that were supplied earlier taken after that config file was applied?
If you can do register dumps with no config applied too, that would be very helpful.
Might be useful to know for the purposes of documenting stuff anyway. ITE should release more datasheets, and improve the quality of their documentation in general ("special FAN extra vector" anyone?). This driver only scratches the surface of what is possible (next aim for me is to get closed loop fan speed control ie setting an rpm value implemented in the driver).
If I was a chip designer and someone said they wanted to improve support for my chips for free I would consider it a no-brainer.

**Comment by konomikitten** [comment] 2018-11-24 17:34
> Are the register dumps that were supplied earlier taken after that config file was applied?

All previous dumps bar my comment previous to this one had the config file applied.

> If you can do register dumps with no config applied too, that would be very helpful.

See the comment before this one for those.

If you need further data happy to give it.
